# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 05a6e271eab615091c0cdb5cef7a15b444cbd72d569409ddaf9924aafea07b5cd089b8392124b4ca91e8c5b28001c26ec1d35f0fc1aad344460a56149c1ed91f

test:
  secret_key_base: 45f61760e796e8b0454a6aedb003a2ea9c787b4a8ce00f5a2768266e131da5307bc2e17e63a3adf3db947ed4634998248c2cc3f0405e6fdcc896442bcbcba679

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
